name: Deploy Portfolio to AWS S3 and CloudFront

# Kịch bản sẽ chạy mỗi khi bạn 'git push' code lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Tải code từ GitHub Repository xuống máy chủ ảo của GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

# 2. Cấu hình thông tin đăng nhập AWS từ Secrets
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3. Tự động đồng bộ (Sync) toàn bộ file lên S3 Bucket và tự xóa file cũ
    - name: Sync files to S3
      run: |
        aws s3 sync . s3://thanhdat-cv --delete --exclude ".git/*" --exclude ".github/*"

    # 4. Tự động xóa Cache của CloudFront để web cập nhật ngay tức thì
    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id E2GP2DD6Q8KXYE --paths "/*"